server:
  port: 8989
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        # 最大连接数 默认8
        max-active: 8
        # 最大空闲连接数 默认8
        max-idle: 8
        # 最小空闲连接数 默认0
        min-idle: 0
